dist: trusty
sudo: required

language: go

go:
 - 1.5.x
 - 1.6.x
 - 1.7.x
 - 1.8.x
 - 1.9.x

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install g++-4.8 libsnappy-dev zlib1g-dev libbz2-dev cmake-data cmake -qq
 - export CXX="g++-4.8" CC="gcc-4.8"

install:
  - cmake -version
  - export SNAPPY_DIR=$HOME/snappy-1.1.3
  - export LEVELDB=$HOME/leveldb-1.18
  - export ROCKSDB=$HOME/rocksdb-5.8
  - export CGO_CFLAGS="-I${LEVELDB}/include/ -I${ROCKSDB}/include/"
  - export CGO_LDFLAGS="-L${LEVELDB} -L${ROCKSDB} -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy"
  - export LD_LIBRARY_PATH="${LEVELDB}:${ROCKSDB}:/usr/local/lib"
  # get and build icu 57.1
  - cd
  - curl -sLO http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-src.tgz
  - tar zxvf icu4c-57_1-src.tgz
  - cd icu/source
  - chmod +x runConfigureICU configure install-sh
  - ./runConfigureICU Linux/gcc
  - make
  - sudo make install
  - icu-config --version
  - export ICU_LD_FLAGS=`icu-config --ldflags`
  - export CGO_LDFLAGS="${CGO_LDFLAGS} ${ICU_LD_FLAGS}"
  # get and build leveldb 1.18
  - cd
  - curl -sLO https://github.com/google/leveldb/archive/v1.18.tar.gz
  - tar zxvf v1.18.tar.gz
  - cd leveldb-1.18
  - make
  # get and build snappy
  - cd
  - curl -sLO https://github.com/google/snappy/releases/download/1.1.3/snappy-1.1.3.tar.gz
  - tar zxvf snappy-1.1.3.tar.gz
  - cd snappy-1.1.3
  - ./configure
  - sudo make install
  # get and build rocksdb
  - cd
  - curl -sLO https://github.com/facebook/rocksdb/archive/v5.8.tar.gz
  - tar zxvf v5.8.tar.gz
  - cd rocksdb-5.8
  - make shared_lib
  # fetch all necessary go deps
  - cd
  - go get github.com/blevesearch/blevex/leveldb/...
  - go get github.com/blevesearch/blevex/rocksdb/...
  - go get github.com/blevesearch/blevex/preload/...
  - go get github.com/blevesearch/blevex/stemmer/...
  - go get github.com/blevesearch/segment
  - go get github.com/blevesearch/blevex/cznicb/...
  - go get github.com/blevesearch/blevex/detectlang/...
  - go get github.com/blevesearch/blevex/lang/ja/...

script:
  - go test -v github.com/blevesearch/blevex/batcher
  - go test -v github.com/blevesearch/blevex/cznicb
  - go test -v github.com/blevesearch/blevex/leveldb
  - go test -v github.com/blevesearch/blevex/rocksdb
  - go test -v github.com/blevesearch/blevex/preload
  - go test -v github.com/blevesearch/blevex/detectlang
  - go test -v github.com/blevesearch/blevex/stemmer
  - go test -v github.com/blevesearch/blevex/icu
  - go test -v github.com/blevesearch/blevex/lang/da
  - go test -v github.com/blevesearch/blevex/lang/de
  - go test -v github.com/blevesearch/blevex/lang/en
  - go test -v github.com/blevesearch/blevex/lang/es
  - go test -v github.com/blevesearch/blevex/lang/fi
  - go test -v github.com/blevesearch/blevex/lang/fr
  - go test -v github.com/blevesearch/blevex/lang/hu
  - go test -v github.com/blevesearch/blevex/lang/it
  - go test -v github.com/blevesearch/blevex/lang/ja
  - go test -v github.com/blevesearch/blevex/lang/nl
  - go test -v github.com/blevesearch/blevex/lang/no
  - go test -v github.com/blevesearch/blevex/lang/pt
  - go test -v github.com/blevesearch/blevex/lang/ro
  - go test -v github.com/blevesearch/blevex/lang/ru
  - go test -v github.com/blevesearch/blevex/lang/sv
  - go test -v github.com/blevesearch/blevex/lang/th
  - go test -v github.com/blevesearch/blevex/lang/tr

notifications:
  email:
    - marty.schoch@gmail.com
